---
- hosts: node
  tasks:
    - name: Creating a user
      user:
        name: Charchit
        state: present 
    - name: Create a File
      file:
        path: /home/ubuntu/hello123
        state: touch
